### ISSUE TITLE
discussion + links

### ISSUE THREAD

**Issue by timotheecour** [genotrance/feud#1]
## IDE's in nim for nim
not sure what's the plugin support with these (good plugin support is indeed fundamental)
* first attempt by araq: https://github.com/nim-lang/Aporia/
* that was since deprecated in favor of https://github.com/Araq/nimedit
* more here: https://github.com/nim-lang/Nim/wiki/Editor-Support

## client/server communication for plugins
* sublime model (uses async)
* RPCS
  * nimtwirp (uses protobuf)
  * GRPC (also supports bidirectional streaming but that feature seems overkill for plugin; i don't know of a nim port)
  * capn'proto (also supports advanced RPC feature to access arbitrary nested data efficiently); has nim ports

### shared memory
* probably simpler for simple things, but may be more complex once you run into memory sharing issues
* need to take care of blocking issues (could freeze editor)
* not good for security (eg if plugins are untrusted)
* a bad plugin could crash the editor
* potentially faster in memory intensive applications; not sure it applies for text editor unless you're dealing with giant files, then it could be relevant
* doesn't help with remote editors

### RPC
* requires serialization/deserialization step (but can be 100% transparent in most cases), eg:
  * using raw nim types, eg: https://github.com/nim-lang/Nim/pull/10346 generic `parse[T](a: string)`
    easy to extend to arbitrary nim types using macros
  * using protobuf (https://github.com/oswjk/nimpb which is faster than https://github.com/PMunch/protobuf-nim)
  * using json; that has some limitations inherent to json; eg needs base64 encoding for binary data etc; but marshall + `%*` from stdlib can be used for serialization/deserialization
  * using bson (https://github.com/SSPkrolik/nimongo nimongo.bson) which addresses some issues with json; more efficient

### scintilla
* + open source
* + C api, making easy to port via nimterop
  https://www.scintilla.org/ScintillaDoc.html#TextRetrievalAndModification
  > ported nimscintilla to nimterop - took 10 minutes!

* not sure how feature-rich compared to sublimetext (including syntax files, tabs, panes within tabs etc)
* not sure how efficient compared to sublimetext (eg large text buffers, 100's of panes)

* not sure how advanced it is compared to sublime

### sublimetext
* - closed source
* + rich plugin API
* - python (type safety etc); but can be wrapped into a nim API, at some cost

## use cases
* editing a remote file; this should be lag-free except maybe on save/load

## misc links
* https://github.com/sieukrem/jn-npp-plugin/wiki/Direct-calls-to-Scintilla

**Comment by genotrance** [comment]
Feud had come quite a ways. Plugin system that started out based on nimterop's has come quite a ways and is working well.

Some plugins use shared memory and threads and feud makes it relatively easy.

RPC has been based on nng and is working fine. Using the bus protocol for now but leverage is still primitive.
