### ISSUE TITLE
Drag & drop does not open files if the filename contains spaces

### ISSUE THREAD

**Issue by xv** [genotrance/feud#2]
Feud is unable to open files when the filename contains a space character. For example, dropping
`C:\LEXER_TESTING\NIM\syntax\test strings.nim` will result in
`File does not exist: C:\LEXER_TESTING\NIM\syntax\test`.

Similarly, opening files with the `open` command without wrapping filenames containing spaces in quotes will exhibit the same behavior.

**Comment by genotrance** [comment]
Thanks for trying out feud! I can fix drag and drop by simply wrapping in quotes. But the open command allows opening multiple files and only way to distinguish multiple files from files with spaces is with quotes.

Curious what's a better path forward - expect quotes or remove ability to open multiple.

**Comment by genotrance** [comment]
I've just pushed a fix for the drag and drop space issue. I've also left the open command as is - i.e. quotes are required for filenames with spaces for now.

**Comment by xv** [comment]
Being able to open multiples is more important, in my opinion. You did best by leaving it as is for now.

Thanks for the quick D&D fix :)

**Comment by genotrance** [comment]
Happy to receive any other feedback. Thanks again.
